require:
  - rubocop-rails
  - rubocop-performance
  # - rubocop-rspec
  # - rubocop-factory_bot

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0

# === BUNDLER =================================================================================== #

Bundler/OrderedGems:
  Enabled: true

# === METRICS =================================================================================== #

Metrics/AbcSize:
  Max: 105

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - 'app/views/**/*'

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 120

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 15

# === LAYOUT ==================================================================================== #

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces
  IndentationWidth: 2

Layout/LineLength:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# === LINT ====================================================================================== #

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/EmptyFile:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RequireParentheses:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

# === NAMING ==================================================================================== #

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Naming/VariableNumber:
  Enabled: false

# === PERFORMANCE =============================================================================== #

Performance/TimesMap:
  Exclude:
    - 'spec/factories.rb'

# === RAILS ===================================================================================== #

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

# === RSPEC ===================================================================================== #

# Give more freedom on context definitions
# RSpec/ContextWording:
#   Enabled: false

# RSpec/LetSetup:
#   Enabled: false

# RSpec/MessageSpies:
#   Enabled: false

# RSpec/MultipleExpectations:
#   Max: 3

# RSpec/MultipleMemoizedHelpers:
#   Enabled: false

# RSpec/NamedSubject:
#   Enabled: false

# RSpec/NestedGroups:
#   Enabled: false


# === STYLE ===================================================================================== #

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
